spring.application.name=placement-tracker
spring.datasource.url=jdbc:mysql://localhost:3306/placement_tracker
spring.datasource.username=root
spring.datasource.password=Mehul@1.2.3.4

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

jwt.secret=PlacementTrackerJwtSecretKeyForSpringBootAuthenticationAndAuthorization2026VerySecureKey